
services:
  mongodb:
    container_name: level-up-english-db
    image: mongo:8
    volumes:
      - vol-mongodb:/data/db
    ports:
      - 27018:27017
  api:
    container_name: level-up-english-api
    build: ./
    env_file: .env
    environment:
      - DB_URL=mongodb://mongodb:27017/level-up-english
    depends_on:
      - mongodb
    restart: on-failure
    ports:
      - 5011:5011

volumes:
  vol-mongodb: 